"""Add privacy columns

Revision ID: 85b958f59fd6
Revises: db5c314910f3
Create Date: 2026-03-11 23:45:00.560177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b958f59fd6'
down_revision = 'db5c314910f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_sharing_consent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notification_preferences', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notification_preferences')
        batch_op.drop_column('data_sharing_consent')

    # ### end Alembic commands ###
