"""add composite index on login_attempts

Revision ID: db5c314910f3
Revises: d29f3cad0574
Create Date: 2026-03-11 21:04:07.818528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db5c314910f3'
down_revision = 'd29f3cad0574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_subscriptions_old')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index('idx_admins_user_id')

    with op.batch_alter_table('adolescents', schema=None) as batch_op:
        batch_op.drop_index('idx_adolescents_user_id')

    with op.batch_alter_table('content_writers', schema=None) as batch_op:
        batch_op.drop_index('idx_content_writers_approved')
        batch_op.drop_index('idx_content_writers_user_id')

    with op.batch_alter_table('health_providers', schema=None) as batch_op:
        batch_op.drop_index('idx_health_providers_user_id')
        batch_op.drop_index('idx_health_providers_verified')

    with op.batch_alter_table('insight_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_insight_cache_user_id')

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_login_attempts_phone_ip_created', ['phone_number', 'ip_address', 'created_at'], unique=False)

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_column('action_label')
        batch_op.drop_column('action_url_template')
        batch_op.drop_column('delivery_channels')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('requires_action')
        batch_op.drop_column('priority')
        batch_op.drop_column('category')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('notifications_sender_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('notifications_related_appointment_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('notifications_related_provider_id_fkey', type_='foreignkey')
        batch_op.drop_column('delivery_channels')
        batch_op.drop_column('action_url')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('metadata')
        batch_op.drop_column('is_delivered')
        batch_op.drop_column('scheduled_for')
        batch_op.drop_column('action_taken_at')
        batch_op.drop_column('priority')
        batch_op.drop_column('requires_action')
        batch_op.drop_column('category')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('action_taken')
        batch_op.drop_column('notification_metadata')
        batch_op.drop_column('action_data')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('action_label')
        batch_op.drop_column('related_appointment_id')
        batch_op.drop_column('custom_data')
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('related_provider_id')
        batch_op.drop_column('real_time_sent')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index('idx_parents_user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_email_trgm', postgresql_using='gin')
        batch_op.drop_index('idx_users_name_trgm', postgresql_using='gin')
        batch_op.drop_index('idx_users_phone_trgm', postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_phone_trgm', ['phone_number'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_users_name_trgm', ['name'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_users_email_trgm', ['email'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_index('idx_parents_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_time_sent', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('related_provider_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custom_data', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('related_appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action_data', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notification_metadata', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action_taken', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('requires_action', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action_taken_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scheduled_for', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_delivered', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('metadata', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('delivery_channels', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('notifications_related_provider_id_fkey', 'health_providers', ['related_provider_id'], ['id'])
        batch_op.create_foreign_key('notifications_related_appointment_id_fkey', 'appointments', ['related_appointment_id'], ['id'])
        batch_op.create_foreign_key('notifications_sender_id_fkey', 'users', ['sender_id'], ['id'])

    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('requires_action', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('delivery_channels', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action_url_template', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_phone_ip_created')

    with op.batch_alter_table('insight_cache', schema=None) as batch_op:
        batch_op.create_index('ix_insight_cache_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('health_providers', schema=None) as batch_op:
        batch_op.create_index('idx_health_providers_verified', ['is_verified'], unique=False)
        batch_op.create_index('idx_health_providers_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('content_writers', schema=None) as batch_op:
        batch_op.create_index('idx_content_writers_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_content_writers_approved', ['is_approved'], unique=False)

    with op.batch_alter_table('adolescents', schema=None) as batch_op:
        batch_op.create_index('idx_adolescents_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index('idx_admins_user_id', ['user_id'], unique=False)

    op.create_table('notification_subscriptions_old',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('app_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sms_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('appointment_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('health_provider_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cycle_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('medication_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('emergency_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('system_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('quiet_hours_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('quiet_hours_start', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('quiet_hours_end', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('real_time_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('websocket_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('subscribed_providers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notification_subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notification_subscriptions_pkey')
    )
    # ### end Alembic commands ###
